### PR TITLE
fix: set minimum gas price

### PR DESCRIPTION
**Pull request by jcs47**

### CODE REVIEW

**Review by sergeynog — APPROVED** [review]

**Comment by sergeynog** [comment]
can we just push a new min fee without causing issues at the consensus? the fee is not on chain, so some validators might end up with the old fee (0), others will set the new fee -- some TXs will be rejected by different sets of validators. We probably need to coordinate & ask all validators to pull the latest / update min-fee at the same time.

**Comment by jcs47** [comment]
> can we just push a new min fee without causing issues at the consensus? the fee is not on chain, so some validators might end up with the old fee (0), others will set the new fee -- some TXs will be rejected by different sets of validators. We probably need to coordinate & ask all validators to pull the latest / update min-fee at the same time.

I think that if this was going to cause issues with the consensus, we would already been seeing consensus failures due to having axelarate-community with no minimum fee

**Comment by sergeynog** [comment]
i don't mean the consensus failures, but some validators will accept a given transaction, others might reject if their fees are set differently.

**Comment by ggutoski** [comment]
> can we just push a new min fee without causing issues at the consensus? 

Not 100% sure here but I _think_ this `minimum-gas-prices` defines a "dust" threshold---unconfirmed transactions with gas prices below this minimum are simply ignored by the validator and not gossiped to everyone else.  They are still legal transactions and can be mined into a block if some validator chooses to do so.

See https://docs.cosmos.network/master/basics/gas-fees.html

> During CheckTx, verify that the gas prices provided with the transaction is greater than the local min-gas-prices (as a reminder, gas-prices can be deducted from the following equation: fees = gas * gas-prices). min-gas-prices is a parameter local to each full-node and used during CheckTx to discard transactions that do not provide a minimum amount of fees. This ensure that the mempool cannot be spammed with garbage transactions.

It's similar to what bitcoin core does---by default bitcoin txs with too small fee are not gossiped.  You need to reconfigure your node to propagate such transactions, and even if you do other nodes can simply choose to ignore.  But miners are still free to put zero-fee txs into blocks if they so choose.

**Comment by milapsheth** [comment]
Hmm, maybe, we should update couple of our validator nodes first to verify if it results in any issues?

**Comment by sergeynog** [comment]
I tried on my validator and was able to send heartbeat. Didn't see any issues.

**Pull request merged**
