### PR TITLE
chore: enforce user to backup mnemonics

### PR DESCRIPTION
**Pull request by sdaveas**
Enforce users to delete their mnemonics before continuing.

### CODE REVIEW

**Comment by ggutoski** [comment]
Looks good.  What about docker?

**Comment by ggutoski** [comment]
As per discussion: need to unify behaviour across docker/binaries as much as possible.  Currently `launch-validator-tools.sh` does `auto` by default, which simply renames the tofnd `export` to `import`.  By contrast, `launch-validator-tools-with-binaries.sh` does not do this.

Let's change `launch-validator-tools.sh` so that the user must explicitly add the `auto` flag in order to get the `export` -> `import` rename behaviour.  If no `auto` flag is set then `launch-validator-tools.sh` behaves like `launch-validator-tools-with-binaries.sh`---ie. it pauses to force the user to do something with the `export` file.

**Comment by sdaveas** [comment]
Mnemonic backup checks are now done for the validator, the broadcaster and tofnd. Added a `--no-backup-enforce` flag at docker scripts to bypass backup checks. No such flag is available at binaries.

**Review by ggutoski — APPROVED** [review]
## Clarification of differences between docker and binary

Default behaviour of `launch-validator-tools.sh` / `launch-validator-tools-with-binaries.sh`
* **Binaries:** User is asked to move the tofnd `export` file
* **Docker:** User is asked to move the tofnd `import` file

These behaviours are almost identical so I'm happy.

Why is the file called `import` in the docker case?  It's much simpler to have a one-step launch process for tofnd inside docker.  This one-step process uses the `auto` command under the hood, which is available only in the docker container.  The `auto` command automatically renames `export` -> `import` so that the tofnd docker container does not need to be launched twice.

For consistency with binaries (and best practice) we still want the user to do something about the tofnd mnemonic, so we ask the user to do something about the `import` file _after_ the tofnd container has successfully launched.  (Compare: with binaries the user must move the `export` file _before_ tofnd launches.)

**Pull request merged**
