### PR TITLE
Revert "chore: remove axelar internal rpc endpoints for ethereum and bitcoin"

### PR DESCRIPTION
**Pull request by Windforcer**
Reverts axelarnetwork/axelarate-community#200

### CODE REVIEW

**Comment by Windforcer** [comment]
It seems the invalid RPC address placeholder in config.toml prevents the axelar testnet node from spinning up for regular usings running the join-testnet.sh script. This revert should fix the issue. This is not critical, as testnet users currently checkout v0.6.0 of the axelarate-community repo during setup, and the problem is on main branch.

**Comment by ggutoski** [comment]
Looks like another effect of #210 .  We should fix that issue instead of merging this PR.  If no one has time then we could merge this PR as a temporary stopgap.

**Comment by Windforcer** [comment]
Agreed, after discussion, we want to fix the issue with join-testnet script failing, rather than reverting the placeholder RPC endpoint change which we want for the next testnet release. Ive created an issue https://github.com/axelarnetwork/axelarate-community/issues/213.

**Comment by Windforcer** [comment]
This PR can be left unmerged, as it does not affect the testnet currently. Users checkout axelarate-community tag v0.6.0 which is working, before joining the network. As long as the issue is addressed before another tag release, we're good to go :)

**Pull request closed without merging**
