### PR TITLE
add faq to documentation site

### PR DESCRIPTION
**Pull request by aditya-manit**
Kate suggested to move the FAQ doc to the documentation site as well

https://discord.com/channels/770814806105128977/855477983938215986/888167244058755123

### CODE REVIEW

**Comment by Windforcer** [comment]
Thanks for migrating the FAQ to vercel :) It looks like the website deployment failed on this branch, could you double check any newly added links and URLs?

**Comment by aditya-manit** [comment]
ahh Strange ! I ran it on my local it was okay 🤔  Let me check and get back to you. Thanks for pointing it out.

**Comment by aditya-manit** [comment]
Also I see the preview failed with 404, usually happens when we are in wrong directory. Meanwhile I check it, just to want to make sure we are doing `cd documentation` before `npm run serve` in vercel configurations right ?

**Comment by Windforcer** [comment]
Yep! We have the /documentation directory set as the root directory (same as cd documentation and npm run serve)
Since I have access to the vercel logs, I can debug this.

Thanks for doing all the migration work!

**Pull request merged**
