### PR TITLE
doc: update exercises 4,5 for toronto testnet

### PR DESCRIPTION
**Pull request by ggutoski**
* Ex4 removed for now until terra is back up.
* Add new page for Metamask setup.
* BEFORE MERGE: coordinate with @aditya-manit on submission form

### CODE REVIEW

**Comment by ggutoski** [comment]
Some indentation issues with the rendering platform:
1. fire quote block `!>` recognized only if it's completely unindented.  Thus, warnings (and everything that follows) are not properly indented in a numbered list.
2. How to make a multi-line fire quote block?  As you can see, prefixing additional lines with `!>` doesn't work.
3. Numbered list items with bulleted sublist causes all subsequent text to be indented too far.  (See "redeem" item 3.)

**Comment by aditya-manit** [comment]
regarding 4 - On light theme it looks okay - I guess it must look bad on dark theme right ? 

fixed: 1,2,4

Can you elaborate on 3 please 😅

**Comment by ggutoski** [comment]
Don't worry about it.  Not worth the trouble right now.

See indentation for items 1,2 compared to 3.  Anything after the bulleted list in 3 is indented too far.

Screenshot 2021-12-17 at 10-53-02 Exercise 5

**Comment by ggutoski** [comment]
> regarding 4 - On light theme it looks okay - I guess it must look bad on dark theme right ?

Ah yes I'm using dark theme.

**Review by haiyizxx — APPROVED** [review]

**Pull request merged**
